name: Deploy Project

on: [workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Check out the repository using checkout action
    - name: Get code
      uses: actions/checkout@v3
    # Install node js using setup-node action with node version 18
    - name: Install node
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: Install dependencies
      run: npm ci
    - name: Run tests
      run: npm run test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Get code
      uses: actions/checkout@v3
    - name: Install node
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: Install dependencies
      run: npm ci
    - name: Build project
      run: npm run build
    - name: Deploy project
      run: echo "Deploying project ..."
