name: Matrix Demo
on: [workflow_dispatch]
# on: push
jobs:
  build:
    # continue on error allows the job to continue even if one of the configurations fails
    continue-on-error: true
    strategy:
      # adding matrix tells github actions to run the job multiple times with different configurations
      matrix:
        node-version: [12, 14, 16]
        operating-system: [ubuntu-latest, windows-latest]
        include:
          - node-version: 18
            operating-system: ubuntu-latest
        exclude:
          - node-version: 12
            operating-system: windows-latest
    # you can access the matrix values using the ${{ matrix.<name> }} syntax
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm ci
      - name: Build project
        run: npm run build
