name: Reusable Deploy
on:
  workflow_call:
    inputs:
      artifact-name:
        description: The name of the deployable artifact files
        required: false
        default: dist
        type: string
    outputs:
      result:
        description: The result of the deployment operation
        # 3. Set the result output of the workflow as the result output of the deploy job
        value: ${{ jobs.deploy.outputs.outcome }}
    # secrets:
      # some-secret:
        # required: false
jobs:
  deploy:
    outputs:
      # 2. Get the result output from 1 and set it as the outcome output of job
      outcome: ${{ steps.set-result.outputs.step-result }}
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
      - name: List files
        run: ls
      - name: Output information
        run: echo "Deploying & uploading..."
      # 1. Set the result output
      - name: Set result outputstep-result=success
        id: set-result
        run: echo "step-result=success" >> $GITHUB_OUTPUT
